### ISSUE TITLE
Rename IStore.Get to IStore.Value

### ISSUE THREAD

**Issue by alfonsogarciacaro** [davedawkins/Sutil#10]
If I'm not mistaken, the convention in .NET is to use names for properties and verbs for methods. So I guess many users will think `Get` must be called as a method (as in ` myStore.Get()`). What do you think?

**Comment by davedawkins** [comment]
Sure, and I agree. We could rename it as Value then it won't need to be a method (my preference, if you agree that would be good design), or make Get into a method.

**Comment by alfonsogarciacaro** [comment]
Yes, a property named Value should work, thanks!
