### ISSUE TITLE
Question: Any ideas for routing?

### ISSUE THREAD

**Issue by marcingolenia** [davedawkins/Sutil#16]
Hi there! 
The stuff you have here seems to be pretty far. I have been thinking about giving it a try and build some kind of small app with routing. Any suggestions/ideas regarding routing? I really like svelte-spa-router;
https://github.com/ItalyPaleAle/svelte-spa-router
Do you plan to build something similar?

**Comment by davedawkins** [comment]
Hi Marcin, thanks for your message.
I will look closer at that page, but I did just add '#'-based routing to the main example App. 
```
let parseUrl (location: Location) =
    let hash =
        if location.hash.Length > 1 then location.hash.Substring 1
        else ""
    if hash.Contains("?") then
        let h = hash.Substring(0, hash.IndexOf("?"))
        h, hash.Substring(h.Length+1)
    else
        hash, ""

let parseDemoView (loc:Location) : DemoView =
    let hash, query = (parseUrl loc)

    match Demo.All |> List.tryFind (fun d -> toHash d.Title = hash) with
    | None -> DemoApp (Demo.All.Head)
    | Some demo ->
        if query = "" then
            DemoApp demo
        else
            // Don't allow '#?../../../etc/passwd'
            if demo.Sources |> List.contains query then
                DemoSrc (demo,query)
            else
                DemoApp demo

let app () =
    Html.app [
        // Page title
        headTitle "Sutil"

        // Bulma style framework
        headStylesheet "https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css"

        // Build the app
        Navigable.navigable parseDemoView <| fun demo ->
            MediaQuery.media "(max-width: 768px)" id (appMain demo)
    ]

app() |> mountElement "sutil-app"
```
How close is that to what you need?

Also - if you know what type of app you'd like to build, I could create the docs / tutorials specifically tailored in that direction. It's good to have  a focus.
Let me know!

Cheers

**Comment by marcingolenia** [comment]
Thanks! That will help me to get started. I am thniking about contact app or sth similar - just to check this and that. Feel free to close the question - when I will have sth to share I will try to reach you again.

**Comment by davedawkins** [comment]
OK no problem. If you can wait until the end of the weekend, I will have uploaded an initial alpha nuget package, with some updates to the navigable stuff. Thanks for checking my stuff out.
