### ISSUE TITLE
Any ideas for a proper Bulma integration?

### ISSUE THREAD

**Issue by bengobeil** [davedawkins/Sutil#17]
Hi,

We can currently use Bulma via css classes, but I am wondering how could we make a proper Bulma integration à la Feliz.Bulma?

Any plans on making first-class styling integrations?

**Comment by davedawkins** [comment]
Definitely, you can see the start of that in App/Bulma.fs in the main repo.
I'll check that in to the main package (or a separate package?) later.
CRUD.fs makes use of Bulma.fs

**Comment by davedawkins** [comment]
I will also take a look at Feliz.Bulma and see what kind of re-use/re-targeting we can achieve

**Comment by bengobeil** [comment]
I saw Feliz.MaterialUI have code generation to create bindings. For sure, I feel we should have a code generated library for Bulma.

**Comment by bengobeil** [comment]
Easier maintenance I feel. Probably scrap the bulma documentation or css file

**Comment by bengobeil** [comment]
It should probably be separate package

**Comment by davedawkins** [comment]
Thanks for the tip on MUI. Also, be aware that Alfonso has created Feliz.Engine, which will complete the Html/Css part of Sutil, with full typesafe support for both html and css. I just have to integrate it.

**Comment by davedawkins** [comment]
So after literally 2 minutes looking at Feliz.Bulma (implying I could be missing many details), I think we can fork that project and *basically* convert every mention of `ReactElement` to `'Element` and make a generic engine, like Alfonso's `Feliz.Engine`.

**Comment by davedawkins** [comment]
Feliz.Engine.Bulma included with Sutil from 1.0.0-alpha-004
