### ISSUE TITLE
Bug report: Error when adding sutil 1.0.0-alpha-006 to SAFE template

### ISSUE THREAD

**Issue by morallito** [davedawkins/Sutil#22]
# Os and SDK versions 
```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
```

```
dotnet --version
5.0.201
```

# Steps to reproduce the error
1 - Change the SAFE template to the `3.0.0-beta001`. To do so, I've just installed the template locally using:
```
dotnet new -i SAFE.Template::3.0.0-beta001
```
2 - Create a new SAFE project using the template:
```
mkdir bug_report
cd bug_report
dotnet new SAFE
```
3 - Restore the project and run
```
dotnet tool restore
dotnet run
```

Until here, everything goes ok. 

4 - Instal the last version of Sutil via nuget
```
dotnet paket add Sutil --version 1.0.0-alpha-006
```

Then, try to run the project and in the Client compilation the following error will happen: 

```
/home/iago-moreira/Desktop/bug/src/Client/.fable/Sutil.1.0.0-alpha-006/Bulma.fs(19,9): (22,10) error FSHARP: No overloads match for method 'div'.

Known type of argument: NodeFactory list

Available overloads:
 - static member Html.div : children:#seq<Fable.React.ReactElement> -> Fable.React.ReactElement // Argument 'children' doesn't match
 - static member Html.div : value:Fable.React.ReactElement -> Fable.React.ReactElement // Argument 'value' doesn't match
 - static member Html.div : value:float -> Fable.React.ReactElement // Argument 'value' doesn't match
 - static member Html.div : value:int -> Fable.React.ReactElement // Argument 'value' doesn't match
 - static member Html.div : value:string -> Fable.React.ReactElement // Argument 'value' doesn't match
 - static member Html.div : xs:IReactProperty list -> Fable.React.ReactElement // Argument 'xs' doesn't match (code 41)
/home/iago-moreira/Desktop/bug/src/Client/.fable/Sutil.1.0.0-alpha-006/Bulma.fs(21,13): (21,30) error FSHARP: No overloads match for method 'select'.

Known type of argument: NodeFactory list

Available overloads:
 - static member Html.select : children:#seq<Fable.React.ReactElement> -> Fable.React.ReactElement // Argument 'children' doesn't match
 - static member Html.select : xs:IReactProperty list -> Fable.React.ReactElement // Argument 'xs' doesn't match (code 41)
/home/iago-moreira/Desktop/bug/src/Client/.fable/Sutil.1.0.0-alpha-006/Bulma.fs(31,53): (31,139) error FSHARP: No overloads match for method 'div'.

Known type of argument: NodeFactory list

Available overloads:
 - static member Html.div : children:#seq<Fable.React.ReactElement> -> Fable.React.ReactElement // Argument 'children' doesn't match
 - static member Html.div : value:Fable.React.ReactElement -> Fable.React.ReactElement // Argument 'value' doesn't match
 - static member Html.div : value:float -> Fable.React.ReactElement // Argument 'value' doesn't match
 - static member Html.div : value:int -> Fable.React.ReactElement // Argument 'value' doesn't match
 - static member Html.div : value:string -> Fable.React.ReactElement // Argument 'value' doesn't match
 - static member Html.div : xs:IReactProperty list -> Fable.React.ReactElement // Argument 'xs' doesn't match (code 41)
/home/iago-moreira/Desktop/bug/src/Client/.fable/Sutil.1.0.0-alpha-006/Bulma.fs(31,93): (31,137) error FSHARP: No overloads match for method 'select'.

Known type of argument: NodeFactory list

Available overloads:
 - static member Html.select : children:#seq<Fable.React.ReactElement> -> Fable.React.ReactElement // Argument 'children' doesn't match
 - static member Html.select : xs:IReactProperty list -> Fable.React.ReactElement // Argument 'xs' doesn't match (code 41)
/home/iago-moreira/Desktop/bug/src/Client/.fable/Sutil.1.0.0-alpha-006/Bulma.fs(73,19): (73,54) error FSHARP: No overloads match for method 'i'.

Known type of argument: NodeFactory list

Available overloads:
 - static member Html.i : children:#seq<Fable.React.ReactElement> -> Fable.React.ReactElement // Argument 'children' doesn't match
 - static member Html.i : value:Fable.React.ReactElement -> Fable.React.ReactElement // Argument 'value' doesn't match
 - static member Html.i : value:float -> Fable.React.ReactElement // Argument 'value' doesn't match
 - static member Html.i : value:int -> Fable.React.ReactElement // Argument 'value' doesn't match
 - static member Html.i : value:string -> Fable.React.ReactElement // Argument 'value' doesn't match
 - static member Html.i : xs:IReactProperty list -> Fable.React.ReactElement // Argument 'xs' doesn't match (code 41)
/home/iago-moreira/Desktop/bug/src/Client/.fable/Sutil.1.0.0-alpha-006/Bulma.fs(84,58): (84,62) error FSHARP: No constructors are available for the type 'Html' (code 1133)
```

# How to solve the error (until a new release fix the bug)
1 - Remove the Sutil from you project
```
dotnet paket remove Sutil 
```
2 - Install the `0.2.1-alpha` version
```
paket add Sutil --version 0.2.1-alpha
```

**Comment by morallito** [comment]
@davedawkins any doubt/help that you need from me, contact me. Congrats for the project, it's amazing!!

**Comment by davedawkins** [comment]
Thanks for the excellent detail in this report. I'll try it out as soon as I can

**Comment by davedawkins** [comment]
Hi, can I just check something? Is the expectation that you can take the SAFE template and that it should compile with no code changes? The code would be very similar, but would at least need changes that replaced `open XXX.React` with `open Sutil`, etc.

You will then need to add `Html.` to any elements that read as just `div`, `p`, `h1` etc. Calls to `str` would need to be changed to `text`. There may be other changes for attributes and css etc.

We can check with Ben to ask him what he needed to change. Let me know!

Dave

**Comment by morallito** [comment]
No, I didn't changed the code because I would like to show you that when I just  download the library to the project, even if I don't call it from any place it breaks.

**Comment by davedawkins** [comment]
OK, I understand. I followed your steps, and the exact same thing does happen for me.

However, it's to be expected. We have given the compiler a new library to compile against that `AutoOpen`s Sutil's modules, and these modules now introduce conflict with the React modules also being opened, *and* the React code that exists in the client. Sutil is a replacement for React, and won't live alongside it (at least not without some care). I admit I didn't expect errors after just installing the package, but I'm certain that's because of the `AutoOpen`s.

After installing the Sutil, the first thing you will need to do is convert the application from React to Sutil, which is what Ben is covering in his series (I hope). I mention some of those steps above.

What I can do is provide a Sutil version of the SAFE client (I created an issue for this).

Does that help explain what's happening?

**Comment by davedawkins** [comment]
Update:
I made some edits to the following files in the SAFE template and eliminated all the errors, and also got the app running:

- src/Client/App.fs
- src/Client/Index.fs
- src/Client/paket.references 
- paket.dependencies 

Changes to App.fs
- Comment all code out, replace with `Index.view() |> Sutil.DOM.mountElement "elmish-app"`

Changes to paket.*
- Remove all references to Feliz / Elmish / React packages

Changes to Index.fs
- Remove all Feliz / React / Elmish opens
```fs
open Sutil.Bulma
open Sutil.Attr
let Bulma = bulma
let prop = Attr
``` 
- .. and a few more tweaks, I'll check this version into a repo so you can see everything.

This is SAFE in Sutil
<img width="708" alt="image" src="https://user-images.githubusercontent.com/285421/112073379-e3877900-8b6b-11eb-9c81-fac7ac36734b.png">

**Comment by morallito** [comment]
Thanks @davedawkins It helped a lot!

**Comment by ruban258** [comment]
I'm using 1.0.0-alpha-006 with a safe-template.
Repo is here, in case anybody else needs a reference.
https://github.com/ruban258/SutilTest
