### ISSUE TITLE
Feature Request: createEventDispatcher

### ISSUE THREAD

**Issue by AngelMunoz** [davedawkins/Sutil#26]
> Rather than keep tweeting about it [Reference from earlier](https://twitter.com/angel_d_munoz/status/1377352260917678080?s=20)

Svelte provides an [event dispatcher](https://svelte.dev/docs#createEventDispatcher) based on `CustomEvents` I think this can be a great addition particularly for Library authors and users, this allows users to emit events from their components and let them listen for them in an ergonomic way in Sutil `on "my-event eventHandler []"` rather than than drilling callbacks or resort to third party thigs like Stores which may not be what you want to rely to if you are authoring components (eg. A calendar emitting a `on-calendar-open` kind of event)

As pointed out in that discussion there's already a few things we can use to reduce boilerplate
https://github.com/davedawkins/Sutil/blob/main/src/Sutil/DOM.fs#L328

what seems to be missing there is how the user can get a reference to the current element which in JS is usually like `this.dispatchEvent(name, opts)`

with some pointers I'd be willing to give it a shot at implementing this (but it can take a while since I'm moving next week)

**edit**: Seems [bind:this](https://svelte.dev/docs#bind_element) is what I might be looking for to ease some of the boilerplate

**Comment by davedawkins** [comment]
I think the best I can offer right now is `hookParent`

```
     Html.div [
        hookParent (fun node -> Browser.Dom.console.log($"div node is {node}"))
     ]
```

Does that help?

I will look at the event dispatcher issue in more detail as soon as I can, I've got myself involved in making bindings of fragments work as expected.

Cheers

**Comment by AngelMunoz** [comment]
I didn't see that one I'll look what I can do with it and report back but as far as I see, it give us the Node reference so we should be able to use it with the existing dispatch functions 

> I will look at the event dispatcher issue in more detail as soon as I can, I've got myself involved in making bindings of fragments work as expected.

No worries, I'm not on a rush once I have a chance as well I'll try to see where I can help

**Comment by davedawkins** [comment]
Ok great. In general I feel that the pattern is breaking down when hooks
like that are needed. I like to look at the problem in general and see if
there's a construct that would work better. I guess that's the custom event
stuff. I'm glad that works for now. We'll see what we can do.

Thanks for all your interest and feedback, it's great to read the tweets

**Comment by AngelMunoz** [comment]
Let me explain myself a little bit more with a specific kind of use case to see if it sheds more light 


I'd like to create self-contained components that receive properties and emit events.

First of all because I look at components as an atomic unit that does something and behaves in a particular way with [CustomEvents](https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent) it is possible leverage the same mechanisms buttons and inputs use to communicate events. For consumers this might not be very important or relevant since you can use stores and elmish to comunicate on different layers but for component authors this can be very important.

I'm not aware if Sutil produces today elements that can be consumed by other Svelte applications but I'd like to have something like this from F#

```fsharp
let TunPaginator(props: PaginatorProps)  = 
   Html.div [
    Html.button [ onClick(fun _ -> ceDispatch('back-pressed')) ]
    ...
    // let's say we're using keyed objects
    Html.button [ text $"%i{i}"; onClick(fun _ -> ceDispatch('page-selected', i)) ]
    ...
  ]
```
and be able to consume it either in an F# application or even a pure Svelte one

```html
<div>
  <tun-paginator {...props} on:back-pressed="..." on:page-selected="..."></tun-paginator>
</div>
```

```fsharp
Html.div [
  on "back-pressed" (fun _ -> elmishDispatch BackPressed) []
  on "page-selected" (fun (e :  CustomEvent<int>) -> elmishDispatch (PageSelected e.detail)) []
  ...
]
```

where `ceDispatch` is basically a convenience or shorcut over creating a `CustomEvent` then dispatching it from the element as shown below 

 ![this.dispatchEvent](https://pbs.twimg.com/media/Ex1V_l_VIAEfxqR?format=png&name=small)

that way we can leave some logic dedicated to how a specific part of the application should behave to the component itself rather than having do that on a page level

Also we may not even need to use the native browser events ourselves, perhaps Svelte can leverage that (it uses them internally) via the [createEventDispatcher](https://svelte.dev/docs#createEventDispatcher) that can leave the door open to author components in F# and let them be consumed everywhere else not just from F#


Please let me know if that give a better insight on my request rather than a simple "feature request" for the sake of requesting it

**Comment by AngelMunoz** [comment]
by the way this is kind of orthogonal to Elmish and Stores, these other two have their own purpose that help with the application overall and this mechanism (props in, events out) does not replace them or should not interrupt them on how they work

**Comment by davedawkins** [comment]
That’s awesome detail and insight. A couple of immediate comments:
- I didn’t see it as a gratuitous feature request, this kind of input is very important, it helps Sutil mature and find its way to being of actual use
- My comment was about the hook itself as a workaround, not the use case. I’m looking forward to working this through.
- One way I have gained access to the DOM Node in the examples I have written, is to use the `Event` passed to any event callback. So if you’re responding to a click, or a mouse move, then you can use `e.Target` as a reference to the node. Its type is `EventTarget` though, and I haven’t figured out a type-safe way to retrieve that as a `Node` other than `e.Target :?> Node`.  In any case, it *is* the Node that received the event. This may be of use, but with your experience, it’s likely you already knew this.

In reading this reply, keep in mind that I haven’t had a chance to read your use case properly yet, and I’ll do that tomorrow with coffee. Again, thanks for the input.

**Comment by davedawkins** [comment]
Finally a chance to read this in detail.

I think `ceDispatch` (as described) can be created as a Sutil helper function that takes the `Event` object and dispatches via `Event.target`. It would be a small wrapper around `dispatchSimple` and `dispatchCustom`.  In fact, this is (almost) exactly what you've done in your `view()` function above. 

I can add that in now - is that enough?

**Comment by davedawkins** [comment]
Something like this
```fs
module Sutil.DOM
//...

type CustomDispatch =
    | Detail of obj
    | Bubbles of bool
    with
        static member toCustomEvent (props : CustomDispatch list) =
            let mutable data : obj = upcast {| |}
            for p in props do
                match p with
                | Detail  d -> Interop.set data "detail" d
                | Bubbles b -> Interop.set data "bubbles" b

        static member dispatch( target : EventTarget, name : string ) =
            dispatchSimple target name

        static member dispatch( e : Event, name : string ) =
            dispatchSimple (e.target) name

        static member dispatch( target : EventTarget, name : string, detail : obj ) =
            dispatch target name (CustomDispatch.toCustomEvent [ Detail detail ])

        static member dispatch( e : Event, name : string, detail : obj ) =
            dispatch (e.target) name (CustomDispatch.toCustomEvent [ Detail detail ])

        static member dispatch( e : Event, name : string, props : CustomDispatch list ) =
            dispatch (e.target) name (CustomDispatch.toCustomEvent props)
```

with usage like this

```fs
    Html.button [
        onClick (fun e -> CustomDispatch.dispatch(e, "back-pressed") []
    ]
    Html.button [
        onClick (fun e -> CustomDispatch.dispatch(e, "page-selected", i) []
    ]
```

**Comment by AngelMunoz** [comment]
I like it I think that should cover most of the cases I think there might be a missing `ICustomEvent<T>` type missing from the fble browser repo which might make this clunky to consume since Event does not have a `detail` property I'll put an issue with them once I have a chance

**Comment by davedawkins** [comment]
Haven't I hidden that level of detail with this interface?  I mean, I'm not ecstatic about the `Interop.set` calls there, but at least setting `detail` is hidden from you.
Are you saying you want an additional overload that takes an `ICustomEvent<T>` too?

**Comment by AngelMunoz** [comment]
> Are you saying you want an additional overload that takes an ICustomEvent<T> too?

No, I meant when consuming the event via `on`
https://github.com/davedawkins/Sutil/blob/main/src/Sutil/Attr.fs#L33

`let on<T> (event : string) (fn : ICustomEvent<T> -> unit) (options : EventModifier list) =  ...` but I think the `ICustomEvent<T>` is missing from Fable.Browser as well

**Comment by davedawkins** [comment]
Oh I see

**Comment by AngelMunoz** [comment]
Hey there, sorry I've been away (I moved from city and started from scratch 😅)

I opened https://github.com/fable-compiler/fable-browser/issues/65 and if it gets merged we can continue working with the CustomEvent<'T> Stuff I was talking about

**Comment by AngelMunoz** [comment]
I was going to give it a shot but I see that you have put the requested things in place 😅 I'll try the new bits and try to get some feedback of them

**Comment by davedawkins** [comment]
No worries! Good luck with the new location! Thanks for the input too

**Comment by AngelMunoz** [comment]
Since #30 is merged I think we can close this
