### ISSUE TITLE
Unwanted each behaviour

### ISSUE THREAD

**Issue by Lanayx** [davedawkins/Sutil#28]
Hi, I'm seeing an unwanted behavior of html elements reordering. Repro:

```fsharp
module App

open Sutil
open Sutil.DOM
open Sutil.Attr

let view() =
    let store = [ "one"; "two"] |> Store.make

    Html.div [
        each store (fun item ->
            Html.div [
                Html.div [
                    text item
                ]
            ]
        ) []
        Html.button [
            text "Add item"
            onClick (fun e ->
                store.Update id
            ) [ PreventDefault ]
        ]
    ]
view() |> mountElement "sutil-app"
```

Once you click on button, it appears on the top of the list
![image](https://user-images.githubusercontent.com/3329606/115400827-6430a800-a1f2-11eb-9d9d-af0897a7c834.png)

**Comment by Lanayx** [comment]
Another issue appeared when I tried to fix the issue above by adding a wrapping div, also changing each to eachi (to enable elements removal)

module App

```fsharp
open Sutil
open Sutil.DOM
open Sutil.Attr

let view() =
    let store = [ "one"; "two"] |> Store.make

    Html.div [
        Html.div [
            eachi store (fun (i, item) ->
                Html.div [
                    Html.span [
                        text item
                    ]
                ]
            ) []
        ]
        Html.button [
            text "Add item"
            onClick (fun e ->
                store.Update (fun items -> "new"::items)
            ) [ PreventDefault ]
        ]
    ]
view() |> mountElement "sutil-app"
```

Once you click Add Item and unhandled exception happens: 
`Uncaught DOMException: Node.removeChild: The node to be removed is not a child of this node`

![image](https://user-images.githubusercontent.com/3329606/115402034-b625fd80-a1f3-11eb-912c-64a5ece27710.png)

**Comment by davedawkins** [comment]
Thanks for this report. I've been working on code related to this issue, and I suspect it's fixed. I'll make this a test case, and check it out tonight.

**Comment by davedawkins** [comment]
Just an update: I've reproduced this and I'm looking into a fix. I'll make sure both these become test cases going forward.

**Comment by Lanayx** [comment]
@davedawkins Hi! I've tried both two cases in REPL and it seems the problems are fixed, should we close this issue?

**Comment by davedawkins** [comment]
Brilliant! Yes, I'll do that now. Thanks for testing, and it's very cool that you tested in the repl :-)
