### ISSUE TITLE
Set Attribute vs Set Property

### ISSUE THREAD

**Issue by AngelMunoz** [davedawkins/Sutil#33]
Right now Sutil sets properties for HTML Elements when using the Binding  utilities and particularly everything that uses `Interop.set`

```fs
[<Emit("$0[$1] = $2")>]
let set<'T> (ob:obj) (name:string) (value:'T) : unit = jsNative
```
This works fine for single named properties but for custom elements, attributes are dash-cased meaning that this will only set properties on elements and this is not what should be done for attributes

```fs
Bind.attr("my-attribute", observable)
```
ends up as
```js
ctx.ParentNode["my-attribute"] =  value
```
A simple workaround is to use a camel cased name instead
```fs
Bind.attr("myAttribute", observable)
```
But, please note that not every attribute corresponds to the same camel cased property (elements can decide wheter to use the same property or a different one when attributes change)

Instead using `Interop.set` for attributes we should use `el.setAttribute(attr, stringValue)`

so we could do the following

```fs
Bind.attr("my-attribute", observable)
```
```js
ctx.ParentNode.setAttribute("my-attribute", stringValue)
```
and also adding a new API for properties which is a valid use case (bind to properties rather than attributes)
```fs
Bind.prop("myAttribute", observable)
```
```js
Interop.set propName value
```

**Comment by davedawkins** [comment]
We have to be careful about behaviour dependent on the spelling of an attribute/property. I'm not aware of a convention with respect to kebab-case vs camel-case either, and wouldn't be able to remember the association. In addition, we convert kebab-case to camel-case to make valid language identifiers.

I think the solution is to use explicitly-named APIs, such as `Bind.attr` and `Bind.prop`, as you say - I like it :-)

**Comment by AngelMunoz** [comment]
Yes this was not well documented since frameworks always focused on adding/removing properties in the html elements, but since web components entered the stage there was some confusion around them https://open-wc.org/guides/knowledge/attributes-and-properties/

**Comment by AngelMunoz** [comment]
also, the reason for attributes and elements to be kebab-case is because when the HTML parser goes through them all of them are always interpreted as lowercase 

e.g `<MyElement withAttributes=""></MyElement>` ends up as `<myelement withatributes=""></myelement>` which is not what you want most of the time, hence why kebab-cased is used for attributes and it's transformed to camel-cased properties by some WC libraries
