### ISSUE TITLE
minor styling nit on sutil.dev

### ISSUE THREAD

**Issue by jpz** [davedawkins/Sutil#37]
Hi,

I saw a small css update it might be worth mentioning.

![55F1D0DD-B29B-48C3-8FD7-DF0B8390816C](https://user-images.githubusercontent.com/934340/127864815-b722bbf2-1909-477c-a831-7c56be64f128.jpeg)

When scrolling the code panel on the RHS, it also scrolls the LHS menu and drags it up, when it should probably stay in place.

If you set overflow-x and possibly overflow-y to "scroll" in the CSS for the RHS pane, I think it should be good - hope this is helpful.

cheers

**Comment by davedawkins** [comment]
I have to admit that I have no business trying to create something like Sutil when I'm still learning how to make CSS work.

Many thanks for this, I will try your idea out.

**Comment by davedawkins** [comment]
This is now fixed, thank you
