### ISSUE TITLE
The type 'Bind' does not define the field, constructor or member 'each'.F# Compiler39

### ISSUE THREAD

**Issue by Pipsy100** [davedawkins/Sutil#41]
The type 'Bind' does not define the field, constructor or member 'each'.F# Compiler39 in SafeClient.fs line 120

**Comment by AngelMunoz** [comment]
Hello, did you try this in the browser or locally? 
@davedawkins I think those changes are still unreleased right?

**Comment by davedawkins** [comment]
I may be behind on a commit. I had to redo some of the Bind.each naming.
Will sync tomorrow

**Comment by davedawkins** [comment]
Everything pushed, packaged, released to nuget and the REPL. Thanks for reporting the issue, and thanks Angel for responding.
