### ISSUE TITLE
Using a web component multiple times overrides prop values

### ISSUE THREAD

**Issue by AngelMunoz** [davedawkins/Sutil#45]
[repl]: https://sutil.dev/repl/#?names=NoIgIgpgZghgrgGwC4DooGcQF0g&codes=NoIgtg9gJgrgNgUwAQEEAOaA6A7HE0LZIDKMALgJZx4FGmVwB0AIgPICyNhJ5VjKZMgCcudXkwDqCAEYBhCGDQRshMgGdRPBo2JkAnnArYA5jjPZ9BJPMXLVABSH41SALxIA3gB8kRimQAuXwskLwBfc0QyawgYCwQhJAAKNCc0NSDdCCEEAB4bJRULR2cAPgBKNxwkGqQopABjWJD3VOckRlLkgDM4pDQkAFoutEY-MnLq2vrxgDUAQzg3frSXL2Gevrb0oZHVsex-SaJphGjjM-k46KTK1tXQjaTeom2XDbeDo-NapAAJMhgJhQCgANyQwCmvxqILUSjUCFY2AAqthINcISt2gBdKHQgBCRigjG6QnmxjAqkazRuL2p1wSu3+gKYZAQAA9ogASTAgDxNBlCCIgY7Q2oAoGMaSJYC4k5iiVMaTkMjKCF437KWSGBoAaw1Ys2RAA+rsDWK3ubobkAH7uZ5bB4bbxYnYAd38AAtgv5lhcyFcQrckABqJAARlCYXKosNv1lVsVjDZnKQvIAktgGjlKRZeVa5XGk8rBGrIfLoVqdfqK3GHSazbXDZam2Lbfa6W8mS6ux6yN7xn7LjTkpVBhGozGrfHC4akynorzmAhswhc2R862kLOFSypSqy1aqxQ9dPavWkKbhmeai247920bXe8uj2Hn2B4dou45otJ7H7whHdoXnDlFxAAAlBAEQ3EACzxYCAHpEOCJA3RkalbCKdQkDUfREBceYciQbAIGieYMEMBAoCQUkFDqChjE9aI2E4CtkNwiAkH7CgXDdZQAHJon4oRdSQBBQW4Chum4z1kDwgxoKQIjkHmKAoGo1D+2QOS1KQCAZO0pAoAgBoYHXJBpD0XDxDxLwug-XRFPVLchHgZBeRBUFeUxWQ1DURgmjgbI0xAHIoB84DfjlHAcmMXi2SEKQ5AUQoqV5NQYEGAV4hEEAYkFTwfEHdwAAYo3MSIzmUjBg3cPEkyIygGkQFyiz3T1I15P4FGQexyQQTd2slBEGkoQ8tyTT0AGZQsDRKSDIJrCOiUqhrnPczLw+ikgyrKcsS3kABpMQEYRApgbawGSXlxmO0K1pFbcAOhKLxT3UbxqIcthqYGa5ppRldGW5TonDUrHsTTbLtVa7dpATLssBvKTuAVBBCEC6rpukA7pAE7eXBx7KmxF7ooQ8wSmMMkwEYdELAAUUQCy9oYQYKKwfKkg525yhAbEgA&html=DwEwlgbgBGILwCIDOBXALmANgWgIYAd8EA+YAenAmKA&css=Q

When you define a web component and use it more than once the last initialization wins over the previous ones, in the [repl] if you click the first counter it will start at 100 rather than 0, the second counter starts at 100 as expected

**As an aside**: Sutil Styling doesn't work with Sutil Web components as seen in the repl above this is mainly because the Shadow DOM already encapsulates the CSS styles so the way Sutil appends styles to the head of the document will not work, this is just a heads up in case someone faces head on with this

**Comment by davedawkins** [comment]
Re: multiple instances - fixed, will be pushed soon. Thanks for spotting this! Solution was to observe immutability while in the JS code. It just reassures me that F# is the way to go in the browser!

I'll look into styling separately
