### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by stroborobo** [davedawkins/Sutil#55]
Hey 👋

maybe I'm super blind right now, but does this project not have a license?

**Comment by davedawkins** [comment]
Possibly, which would be an oversight on my part. I'll fix that

**Comment by stroborobo** [comment]
Thanks! I'm just starting out with this, but I really enjoy your project <3

Take care!

**Comment by davedawkins** [comment]
Now MIT licensed - I simply chose the same as Fable.

**Comment by davedawkins** [comment]
Thank you for your kind words
