### ISSUE TITLE
checkbox has checked=false when used with two way binding

### ISSUE THREAD

**Issue by hesxenon** [davedawkins/Sutil#67]
Hi, as you can see [here in this REPL](https://sutil.dev/repl/#?names=NoIgwgFgpgxg1gIwPYA8CSA7ADgVwC4DOAdAGYEgC6QA&codes=NoIgtg9gJgrgNgUwAQGEAWCDGBrARhADwEkA7ABxgBcBnAHRPoHpGkBBKAQzMoSiQDMAThDBMWaSpTLUAXM2oA3BHB4A6KAgWMEBDmDKI6DEhDIISSAMpUAlnHqnzV23FUARAPIBZB2YvXKO1VWSUFfJwCggBVBDhJqG0CIY3pESiQATwRqJABeK0oIQQRVMA5sBAAKfg44agQASlSEdJgyTh4kEh10-KycgB4APy6IdO6CSnpm9IUbBAB3Soa8+iR1pAAJSjBXKBsFJGBpiw2z7d31A6O1s7v1zDgOamoAciRaEFw4CBxP2-u5x2rieuGUN1OgMBF1cNnIVAhUKRG0oGTM70+mAwOHwBH+kORgIAQnCoKoOKEkJVMdiKlBPgAafoMpBtDqNAGE9YAXU5XJ4kw+ICQAFESBxvsgEAArLCFQRIeoU-Fc3kEs5qvkbGFXQ7HdWAx7PN5C76-bAqwnUNAQBZEfgiurIfpa5GVHVkdbAJAC9KfACaEBgSA4xSQxQ4UAyAiKSCeMBIWM+SG5TQNbo9Xp9PSFgeDC2Sr3SYKQAHMIHDSyGSBkFhgwwnDDkMkGkOYJYgfRg27LMPLFQhlcLU66UycoTr9nrR2cjS8MV8fn8QDPtcDVLgqIULPquWcSSQyRTKArqSB9tQO7xGZlskgAD4APgKRRKZU9Jkoab3KJznwAMhwCZJiu6Z3GqUIQRsapzIsywPs+AAKwilrEYClEGJCUI6CBgOYfogNQLgALRcGQ+IgNyQA&html=DwQgIg8gwgKgmgBQKIAIAWAXAtgGwHwBQwmuKOAhgHYDmAvAEQCml9hxj5AJoSrysFkYZyKAMZpyAJwDOQhgFUYAMQC0ADlYE+-QcPQYMABxWMAjgFcAlgDcGADRXyAgiqgB7LIfIZLAIxyM9GJulBjMGAwAkki0jJzUgTx8AkIilOSCDNaWjADuhm6SGEGiIWGhDLmWnBhotJyM2aKMKlU1aAA0KJaUlj7kOCrSogOMtACMAHQADJrawDg9ANYokow4DIZrOG5cQWhrAGYMmEbSAFwA9JeinJSTAFbSDYvWkpOUQpeUhliXvuYcFhyAABaaTACck3GN2k0n+gOBkywPUmojhQXI0gY0gwAE8AnNkotKCttjj8QFpGhGEJ9kcTgZDBdrrd7k8XjZ3p8MN9fgigaDwVCYej4QDBcjUWKibwFstVusKQTGNTacV0Az6KdmVcbncnmiduZOIcKGs0R5LuQHuQAB6XRa+eGHMoqci5VUeRiXAAskwA7DNYS63R6vYIpfcZUk5T4MAE8ABlcw+HDAS7xxNaZK4lWx7QoXxuTh4lAAbxzhb4wMk1B65xQ4wATIY7QBuKuFgC+Xbllzz2YzNK4bGLpYLwE4Nm6nBxqcsg3IhkMrAz0+sbH+JbxW5I+CAA&css=Q) the checkbox is initialized with `checked="false"` even though the bool representing the checked value is `false`.

This seems to happen only for two way binding though...

**Comment by davedawkins** [comment]
Thanks for reporting this. I will look into this.

**Comment by davedawkins** [comment]
This is fixed. After testing should be available in next release (1.0.0-beta-024)

**Comment by davedawkins** [comment]
Available in 2.x
