### ISSUE TITLE
New nuget release including Bind.radioValue ?

### ISSUE THREAD

**Issue by PierreYvesR** [davedawkins/Sutil#73]
I've just updated my code to Sutil 2 from version 1.
It's been fairly smooth except for radio groups: the current nuget package doesn't include Bind.radioValue, so I had to build against a local copy of the latest code.
When do you expect to do a new nuget release?

I also found that I was using quite a few functions from the Interop module that is now Internal - so I just had to roll out my own.

**Comment by davedawkins** [comment]
I've got a 2.0.1 ready to go, let me know which interop in particular we useful. I also had the same problem with my own projects so next release is mainly to address the same issues you had.

**Comment by PierreYvesR** [comment]
I use `Interop.Window` methods, as well as `Interop.dispatch` and `Interop.dispatchSimple`

**Comment by davedawkins** [comment]
So my recommendation is to use the `Browser.Dom` / `Browser.Types` directly for Window methods. `Sutil.Interop.Window` is an impoverished wrapper that (at one point) allowed me to write tests that did not have a Window defined. Here are the definitions (though you've probably seen them):

```fs
type Window() =
    static member alert msg =
        if windowIsDefined then window.alert msg
    static member document =
        if windowIsDefined then window.document else null
    static member location =
        if windowIsDefined then window.location else null
    static member addEventListener(typ,listener) =
        if windowIsDefined then window.addEventListener(typ,listener)
    static member getComputedStyle(elt) =
        if windowIsDefined then window.getComputedStyle(elt) else null
    static member getComputedStyle(elt,pseudoElt) =
        if windowIsDefined then window.getComputedStyle(elt,pseudoElt) else null
    static member matchMedia query =
        if windowIsDefined then window.matchMedia query else null
    static member removeEventListener(typ,listener) =
        if windowIsDefined then window.removeEventListener(typ,listener)
    static member requestAnimationFrame callback =
        if windowIsDefined then window.requestAnimationFrame callback else 0.0
```

For `Interop.dispatchSimple target name`, (right now) use `CustomDispatch<unit>.dispatch( target, name)`

For `Interop.dispatch target name data`, (right now) you *could* use
```fs
CustomDispatch<obj>.dispatch( target, name, [ Detail (Some data) ] )
```

but I thihk I'm going to simplify that API a little. I don't know why I made Detail use an optional type.

You will be able to do this instead in the new release
```fs
    CustomDispatch<_>.dispatch( t, n, [ Detail data ] )
```

or just

```fs
    CustomDispatch<_>.dispatch( t, n, data )
```

**Comment by PierreYvesR** [comment]
Thank you for the new 2.0.1 release.

**Comment by davedawkins** [comment]
You're welcome. Please let me know of any issues, and if the fixes you needed work for you

**Comment by PierreYvesR** [comment]
@davedawkins I migrated most of my custom code to the new functions you suggested. It works well and I have less custom code ;) So once again, thank you.
I experienced one small performance issue: if the object are large, the logging line at https://github.com/davedawkins/Sutil/blob/2ecd9fdaff97bc982f6860e4347cfe07c1672ef1/src/Sutil/Bindings.fs#L44 does take a not insignificant amount of time (I see a lot of toString in my profiler). Do you want me to create a separate issue/PR for that?

**Comment by davedawkins** [comment]
I will remove the log statement and build a new package. I may #ifdef them
out or see if there's an attribute that removes them at compile time (C#
had something like that, so in theory should work for F# should too)

**Comment by davedawkins** [comment]
2.0.3 is now available, and should solve the performance issue. I'd like to know how you do performance testing please
