### ISSUE TITLE
Many pages of the documentation don't load properly

### ISSUE THREAD

**Issue by d4h0** [davedawkins/Sutil#76]
Hi,

There seems to be an issue with the documentation. When I go to https://sutil.dev/#documentation-html, for example, the main area stays empty.

There is a lot logged to the console, including the following two errors:

```
TypeError: Cannot read properties of null (reading 'ownerDocument')
Uncaught (in promise) Error: Child not found
```

**Comment by davedawkins** [comment]
Oh boy what did I do..I can fix this later tonight

**Comment by davedawkins** [comment]
This is fixed with a temporary patch which disables the `Open in REPL` buttons. I need daylight and coffee to fix it properly.

**Comment by davedawkins** [comment]
Found root cause, fixed and uploaded

**Comment by d4h0** [comment]
Thanks, @davedawkins!
