### ISSUE TITLE
Getting Started docs 

### ISSUE THREAD

**Issue by HarryMcCarney** [davedawkins/Sutil#77]
Maybe i am doing something daft or these are out of date

On (https://sutil.dev/#documentation-from-a-template)
dotnet new install Sutil.Templates
returns
Sutil.Templates could not be installed, the package does not exist.

And 

On (https://sutil.dev/#documentation-from-scratch)
after also running npm install and npm run start 
C:/Users/harry/StaticAuth/src/App.fs(3,6): (3,11) error FSHARP: The namespace or module 'Sutil' is not defined. (code 39)
C:/Users/harry/StaticAuth/src/App.fs(5,14): (5,18) error FSHARP: The value, namespace, type or module 'Html' is not defined. (code 39)
C:/Users/harry/StaticAuth/src/App.fs(7,11): (7,18) error FSHARP: The value, namespace, type or module 'Program' is not defined. (code 39)

Am running dotnet 6.0.401 on windows 11

**Comment by davedawkins** [comment]
Looking into it...

**Comment by davedawkins** [comment]
Let me review the "from scatch " stuff now...

**Comment by davedawkins** [comment]
Those docs (from_scratch) are also updated. The main problem there was that the Fable template included package references that are older than those being used by Sutil. The doc updates will lead to the latest Sutil package and Fable template being used, but also include the instructions to fix the package issues.

The "from_scratch" instructions were useful to me in showing how to take a basic Fable app and then add Sutil to it. I think now though that it's just easier to use the templates. I've added the `hello world` template to `Fable.Sutil.Templates` to make it easier to get started with the simplest app

```shell
% dotnet new install Fable.Sutil.Templates::2.0.4
The following template packages will be installed:
   Fable.Sutil.Templates::2.0.4

Success: Fable.Sutil.Templates::2.0.4 installed the following templates:
Template Name            Short Name   Language  Tags              
-----------------------  -----------  --------  ------------------
Fable Sutil App          sutil-app    F#        Fsharp/Fable/Sutil
Fable Sutil Hello World  sutil-hello  F#        Fsharp/Fable/Sutil
```

**Comment by HarryMcCarney** [comment]
Thanks Dave, Both approaches now work on my machine.. 

For the "From Scratch" approach.  I did need to run 

% dotnet remove package Fable.Browser.Dom
% dotnet remove package Fable.Core

**Comment by davedawkins** [comment]
> For the "From Scratch" approach. I did need to run
> % dotnet remove package Fable.Browser.Dom
> % dotnet remove package Fable.Core

Yes, me too. There's a chance the Fable template will come up-to-date, or I learn a better way to package Sutil and then suddenly we don't need to do that any more.

Glad it's working.
