### ISSUE TITLE
Sveltish needs its own name?

### ISSUE THREAD

**Issue by davedawkins** [davedawkins/Sutil#8]
As suggested by @alfonsogarciacaro , Sveltish could use its own identity.  This will encourage its growth beyond its initial inspiration, which is undoubtedly Svelte.

Some initial plays on the word "Svelte":
- Belto (Esbelto is Spanish for "svelte")  (edit: correction to Esbelto)
- Langsing (Indonesian for "svelte/slim")
- Pico / Nano (small - Sveltish is relatively small for what it does. HelloWorld is around 26kb)
- <some random word that doesn't need to mean anything at all>

Aspects of Sveltish to consider:
- Small (hence belto/langsing/pico/nano etc)
- Self-contained / no dependencies (eg, it's not using React)
- F#  / functional
- Batteries-included front-end dev for Fable
- Supports MVU (Elmish / Elm)
- It's (another!) front-end framework

**Comment by kaashyapan** [comment]
Belto / Asbelto - Spanish in honor of Alfonso. Maybe a logo can be something with funny hair

**Comment by alfonsogarciacaro** [comment]
Ah, so this is where "Belto" comes from. I think the Spanish word is "Esbelto" but I didn't make the association 😅 There's a popular comedian in Spain called "Berto" and it actually reminded me of him :wink: If you want something in Spanish I can suggest "Sutil", which usually has the meaning of "subtle" but is also a synonym of "esbelto" and adds an association with being "light" (as in Nano). It also plays well with "Feliz" :)

**Comment by davedawkins** [comment]
Re: "Belto" Yes! I translated Svelte to Spanish and just took off the "Es" (I made mistake, now corrected, in the top comment). OK, no comedian associations. :-D

**Comment by zetashift** [comment]
Sutil sounds great!

**Comment by davedawkins** [comment]
Well I bought sutil.dev (and sveltish.dev, just in case). I've worked out how to pronounce sutil, and I think it flows nicely. It's looking like a winner.
