### ISSUE TITLE
Browser navigation and node rebuilds

### ISSUE THREAD

**Issue by kaashyapan** [davedawkins/Sutil#83]
I have a store with a list of elements that I am building out using Bind.each.
I implemented a manual push state into browser navigation history and moved to add a new item to the list.
1) After adding the new element clicking on the back button is not triggering a rebuild of the nodes. i.e new element is not displayed. I still see the old list although the store value is updated.

2) Also my understanding is that unMount should be invoked every time a SutilElement is moved out of the node tree.
Appears this is also not happening

How do I work around these ?

**Comment by kaashyapan** [comment]
Sample repo to reproduce the problem
https://github.com/kaashyapan/sutil-bindlist-error.git

1) Click edit a user and in the user page change email.
2) See from console that the master store value has been updated. Click on back arrow to push history state.
3) Again click on edit user and note the following error in the console
[Log] error: Disposing #2=null: Error: The given key '#2=null' was not present in the dictionary. from <div>#2 "Users" (Logging.fs.js, line 68)

1) Click edit a user and in the user page change email.
2) See from console that the master store value has been updated. Click on browser back button.
3) Note the following error in the console
[Log] error: Disposing #4=null: Error: The given key '#4=null' was not present in the dictionary. from <div>#2 "" (Logging.fs.js, line 68)

[Log] error: Disposing #3=null: Error: The given key '#3=null' was not present in the dictionary. from <div>#2 "" (Logging.fs.js, line 68)

**Comment by davedawkins** [comment]
Thanks for the repo. I'll take a look and get back to you.

**Comment by davedawkins** [comment]
Here's what I think the main problem is:

User.fs:
```fs
            disposeOnUnmount [ user; loading ]
```

and 

Users.fs
```fs
            disposeOnUnmount  [ loading ]
```

The stores `loading` and `user` are globals stores, and so only 1 instance of each exists. Yet, each time we leave the User or Users page, we have asked Sutil to dispose those stores. The first time this will work of course, but the second time ,we are are attempting to dispose stores that have already been disposed. 

You either need to have a new instance of these stores belonging to the respective `view()` functions, or just don't dispose them until the application quits (which you don't really need to do)

**Comment by kaashyapan** [comment]
Thanks for your response.
My first code had the stores inside the module. Which apparently doesn't work because of the way Fable translates the code.
Moving the stores inside the view function works.
