### ISSUE TITLE
project.assets.json does not exist

### ISSUE THREAD

**Issue by KingKnecht** [davedawkins/Sutil#86]
Hi,
I used the `dotnet new suti-app` command to create a project.
If I open the folder with VsCode I get the following error in every *.fs file:

![image](https://github.com/user-attachments/assets/884c1c7e-e233-47de-8eb6-2c9d5d621807)

If I do a `dotnet build  App.fsproj ` everthing compiles. `npm run start` provides the webpage.
But of course with this error I don't have intellisense and every file is marked red.

Any ideas how to fix that?

**Comment by davedawkins** [comment]
Thanks for this report. I've never seen this error before, and I'm not sure what it means, but I will look into it.

**Comment by davedawkins** [comment]
Can you try
```
dotnet restore
```

(according to this page https://stackoverflow.com/questions/48440223/assets-file-project-assets-json-not-found-run-a-nuget-package-restore)

**Comment by KingKnecht** [comment]
Sorry foe the late repsonse. 
I already did. And the FSharp project compiles. But the error is still there. Maybe it's a problem with Ionide and .Net6?

**Comment by KingKnecht** [comment]
Asked the guys from the FSharp language server project
[Issue](https://github.com/fsprojects/fsharp-language-server/issues/117)

**Comment by baronfel** [comment]
Are you actually using fsharp-language-server or are you using Ionide? The former is very out of date.

**Comment by KingKnecht** [comment]
Well, I think both...
![image](https://github.com/user-attachments/assets/17f59442-1441-4aad-a849-2c4cd5c73123)

If I disable the language server, I have no errors. But I do not get Intellisense or signatures of functions. I thought, that is what the language server does, no?

**Comment by baronfel** [comment]
F# language server is a very old project that intended to compete with Ionide. Ionide includes the FsAutocomplete LSP implementation for F#. You shouldn't have both installed ever IMO (I'm the maintainer of Ionide).

**Comment by KingKnecht** [comment]
Woohoo! 
No errors and function signatures!

**Comment by davedawkins** [comment]
Thank you Chet!

**Comment by baronfel** [comment]
Glad that fixed things for you @KingKnecht :)
